server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            -Path=/api/orders/**
          filters:
            name: CircuitBreaker
            args:
              name: order-cb
              fallbackUri: forward:/fallback/orders
        - id: pricing-service
          uri: lb://pricing-service
          predicates:
            - Path=/api/pricing/**
          filters:
            name: CircuitBreaker
            args:
              name: pricing-cb
              fallbackUri: forward:/fallback/pricing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 5
        slidingWindowSize: 10

    instances:
      order-cb:
        base-config: default
      pricing-cb:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: "*"